import 'package:flutter/material.dart';
import 'package:spectrocough/theme/app_colors.dart';

class DisclaimerCard extends StatelessWidget {

  const DisclaimerCard({super.key});

  @override
  Widget build(BuildContext context) {

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: AppColors.warning.withValues(alpha: 0.07),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(
          color: AppColors.warning.withValues(alpha: 0.22),
        ),
      ),
      child: const Text(
        "This report is generated by an AI-based respiratory "
            "screening system and is NOT a medical diagnosis.\n\n"
            "Do not self-diagnose based on this report.\n\n"
            "If symptoms persist consult a healthcare professional.",
        style: TextStyle(height: 1.6),
      ),
    );
  }
}